#!/bin/bash

SCRIPTLOC=`dirname $0`
cd $SCRIPTLOC

DB_LOCATION=`${SCRIPTLOC}/../bin/getProperty dbName`
WEB_ROOT=`${SCRIPTLOC}/../bin/getProperty webRoot`


function extractData() {
  OS=`uname`
  EXT=""
  if [[ $OS == 'Darwin' ]]; then
    EXT=".tmp"
  fi

  cp template extractScript
  sed -i ${EXT} "s/#FILENAME/${1}/g" extractScript
  sed -i ${EXT} "s/#LIFTNAME/${2}/g" extractScript
  sed -i ${EXT} "s/#REPS/${3}/g" extractScript

  sqlite3 $DB_LOCATION < extractScript

  echo "created data/$1"
  rm extractScript
  if [[ $OS == 'Darwin' ]]; then
    rm extractScript.tmp
  fi
}

function extractLift() {
  extractData "${1}1RM" "${2}" 1
  extractData "${1}3RM" "${2}" 3
  extractData "${1}5RM" "${2}" 5
}

if [[ ! -e data ]]; then
  mkdir data
fi

if [[ ! -e svg ]]; then
  mkdir svg
fi

if [[ ! -e $WEB_ROOT/svg ]]; then
  mkdir $WEB_ROOT/svg
fi

extractLift deadlift Deadlift
extractLift backsquat "Back Squat"
extractLift overheadsquat "Overhead Squat"
extractLift cleanandjerk "Clean \& Jerk"
extractLift snatch "Snatch"
extractLift clean "Clean"
extractLift frontsquat "Front Squat"
extractLift shoulderpress "Shoulder Press"
extractLift pushpress "Push Press"
extractLift pushjerk "Push Jerk"
extractLift sotspress "Sots Press"
extractLift squatsnatch "Squat Snatch"
extractLift squatclean "Squat Clean"

gnuplot input.gpi

#cleanup data
rm -rf data
mv svg/* $WEB_ROOT/svg
rm -rf svg

